image: parsertongue/ubuntu:20.04

stages:
  - test
  - deploy

test:
  stage: test
  image: python:3.8
  before_script:
    # store commit
    - export SHORT_COMMIT=$(git rev-parse --short HEAD)
    - "echo 'commit: ${SHORT_COMMIT}'"
  script:
    - pip install -e ".[all]"
    - green -vvv --run-coverage .
    - mypy --ignore-missing-imports --follow-imports=skip --strict-optional .

deploy:
  only:
    # only publish docker images, etc. for commits to master
    refs:
      - master
      #- dev
  # tags:
  #   - docker
  #   - arizona
  stage: deploy
 
  image: parsertongue/ubuntu:20.04
  # see https://docs.gitlab.com/ee/ci/variables/predefined_variables.html
  # see https://docs.gitlab.com/ee/api/deploy_tokens.html
  # see https://docs.gitlab.com/ee/user/project/deploy_tokens/index.html#creating-a-deploy-token
  before_script:
    - export SHORT_COMMIT=$(git rev-parse --short HEAD)
    - "echo 'commit: ${SHORT_COMMIT}'"
    - docker build -f Dockerfile -t "${PROJECT_DOCKER_REGISTRY}:latest" -t "${PROJECT_DOCKER_REGISTRY}:${SHORT_COMMIT}" .
    - docker login -u $CI_USER -p $CI_BUILD_TOKEN $CI_REGISTRY
  script:
    # push all tags
    - docker push $PROJECT_DOCKER_REGISTRY